### ISSUE TITLE
Add CSS styles to login and sign up pages for the Flask App

### ISSUE THREAD

**Issue by Samyak2** [dscpesu/recipe-viewer#1]
## The issue

 - The login and signup pages are currently written in pure HTML.
 - It looks very plain and unappealing.

## Guidlines

 - Add the CSS file to the `static` directory and link it to the corresponding HTML file in `templates` directory OR add the style directly to the HTML file.
 - Send the PR to [this repo](https://github.com/Samyak2/Recipe-viewer-flask-app), it will be merged here.

**Comment by psiayn** [comment]
Can you assign me to it?

**Comment by Samyak2** [comment]
Done

**Comment by Samyak2** [comment]
Thank you for your contributions!

**Comment by Samyak2** [comment]
Closed [here](https://github.com/Samyak2/Recipe-viewer-flask-app/pull/4)
